version: "3"
services:
  ktor-server:
    image: bredfen/apoteka-back:1.0.3
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - mongo
    restart: always
    environment:
      PORT: 80

  db:
    image: mongo:6.0.9
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: myDatabase
    ports:
      - "27017:27017"
    volumes:
      - ./localvolumes/mongo:/data/db
    networks:
      - mongo
    restart: always
networks:
  mongo:
    driver: bridge